eggman:
  development:
    host: http://wechat.g-wq.com

    wechat_id: gh_bf990c842454
    app_id: wxf042081b414afb0b
    app_secret: 8fe00efee4442d630b2b37ea37f64cae

    oauth2_redirect_uri: "http://wechat.g-wq.com/wechat/users/callback"

    push_url: "http://wechat.g-wq.com/wechat/push"
    push_token: <%= ENV['WECHAT_DEV_SANDBOX_PUSH_TOKEN']
  production:
    host: https://g-wq.com

    wechat_id: gh_bf990c842454
    app_id: wxf042081b414afb0b
    app_secret: 8fe00efee4442d630b2b37ea37f64cae